#ifndef __AGILE_UPGRADE_CONFIG_H
#define __AGILE_UPGRADE_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#define AGILE_UPGRADE_ENABLE_LOG
#define AGILE_UPGRADE_LOG_PRINTF printf

#define AGILE_UPGRADE_USING_CRC_TAB_CONST

#define AGILE_UPGRADE_ENABLE_AES
#define AGILE_UPGRADE_AES_IV  "0123456789ABCDEF"
#define AGILE_UPGRADE_AES_KEY "0123456789ABCDEF0123456789ABCDEF"

#define AGILE_UPGRADE_ENABLE_FASTLZ
#define AGILE_UPGRADE_ENABLE_QUICKLZ

//#define AGILE_UPGRADE_ENABLE_FAL
#define AGILE_UPGRADE_ENABLE_FILE

// #define AGILE_UPGRADE_ENABLE_VERSION_COMPARE

#ifdef __cplusplus
}
#endif

#endif /* __AGILE_UPGRADE_CONFIG_H */
